### ISSUE TITLE
Create Post for classes

### ISSUE THREAD

**Issue by ashleymlaing** [Resilient-Labs/Level-Ground#3]
Each class need to be able to loop on a section of the classes.html page.

{% for post in site.categories.CATEGORYNAMEHERE %}
   {{ post.content }}
{% endfor %}

The plan is for the classes to show in place of what I have the white boxes for the classes.

**Comment by leonnoel** [comment]
@ashleymlaing  Is this different then the Mind-Body list? 

They just need a place to put 4 posts describing the classes? 

Do we have a design for what it should look like

**Comment by ashleymlaing** [comment]
@leonnoel  yes it is different, it is so they can input different classes

the mind-body is to sign up for the classes only.

I have the look of it on the classes html page

I do not know how many classes they will put up. we might have to limit the number of post to show.
